const MAP = [
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe2, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, null, null, null],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, null, null, null],
	[IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, IMAGES.herbe1, null, null, null]
];
