IMAGES = {};

IMAGES.GRASS1 = IMAGES_FOLDER + 'terrains/Land1a_00002.png';
IMAGES.GRASS2 = IMAGES_FOLDER + 'terrains/Land1a_00003.png';
IMAGES.GRASS3 = IMAGES_FOLDER + 'terrains/Land1a_00004.png';
IMAGES.INDICATORN = IMAGES_FOLDER + 'terrains/land3a_00089.png';
IMAGES.INDICATORW = IMAGES_FOLDER + 'terrains/land3a_00090.png';
IMAGES.INDICATORS = IMAGES_FOLDER + 'terrains/land3a_00091.png';
IMAGES.INDICATORE = IMAGES_FOLDER + 'terrains/land3a_00092.png';
IMAGES.MOUNTAIN1 = IMAGES_FOLDER + 'terrains/land3a_00083.png';
IMAGES.GRANARY_BASE0 = IMAGES_FOLDER + 'grenier/Commerce_00140.png';
IMAGES.GRANARY_BASE1 = IMAGES_FOLDER + 'grenier/Commerce_00141.png';
IMAGES.GRANARY_STOCK0 = IMAGES_FOLDER + 'grenier/Commerce_00142.png';
IMAGES.GRANARY_STOCK1 = IMAGES_FOLDER + 'grenier/Commerce_00143.png';
IMAGES.GRANARY_STOCK2 = IMAGES_FOLDER + 'grenier/Commerce_00144.png';
IMAGES.GRANARY_STOCK3 = IMAGES_FOLDER + 'grenier/Commerce_00145.png';
